version: '3.8'

services:
  # Database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - recipe-network

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - recipe-network

  # Authentication Service
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8000:8000"
      - "9090:9090"  # Prometheus metrics port
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - DB_NAME=recipe_app
      - SECRET_KEY=your-secret-key-for-development
    depends_on:
      - mongodb
    networks:
      - recipe-network

  # Recipe Service
  recipe-service:
    build: ./backend/recipe-service
    container_name: recipe-service
    restart: always
    ports:
      - "8001:8000"
      - "9091:9090"  # Prometheus metrics port
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - DB_NAME=recipe_app
      - AUTH_SERVICE_URL=http://auth-service:8000
      - RABBITMQ_URI=amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb
      - auth-service
      - rabbitmq
    networks:
      - recipe-network

  # Ingredient Scanner Service
  ingredient-scanner-service:
    build: ./backend/ingredient-scanner-service
    container_name: ingredient-scanner-service
    restart: always
    ports:
      - "8002:8000"
      - "9092:9090"  # Prometheus metrics port
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - DB_NAME=recipe_app
      - AUTH_SERVICE_URL=http://auth-service:8000
      - RABBITMQ_URI=amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb
      - auth-service
      - rabbitmq
    networks:
      - recipe-network

  # Meal Planning Service
  meal-planning-service:
    build: ./backend/meal-planning-service
    container_name: meal-planning-service
    restart: always
    ports:
      - "8003:8000"
      - "9093:9090"  # Prometheus metrics port
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - DB_NAME=recipe_app
      - AUTH_SERVICE_URL=http://auth-service:8000
      - RECIPE_SERVICE_URL=http://recipe-service:8000
      - RABBITMQ_URI=amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb
      - auth-service
      - recipe-service
      - rabbitmq
    networks:
      - recipe-network

  # Shopping List Service
  shopping-list-service:
    build: ./backend/shopping-list-service
    container_name: shopping-list-service
    restart: always
    ports:
      - "8004:8000"
      - "9094:9090"  # Prometheus metrics port
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - DB_NAME=recipe_app
      - AUTH_SERVICE_URL=http://auth-service:8000
      - MEAL_PLANNING_SERVICE_URL=http://meal-planning-service:8000
      - RABBITMQ_URI=amqp://admin:password@rabbitmq:5672
    depends_on:
      - mongodb
      - auth-service
      - meal-planning-service
      - rabbitmq
    networks:
      - recipe-network

  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - auth-service
      - recipe-service
      - ingredient-scanner-service
      - meal-planning-service
      - shopping-list-service
    networks:
      - recipe-network

  # API Gateway
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - recipe-service
      - ingredient-scanner-service
      - meal-planning-service
      - shopping-list-service
      - frontend
    networks:
      - recipe-network

  # Monitoring Stack
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9095:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - recipe-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - recipe-network

networks:
  recipe-network:
    driver: bridge

volumes:
  mongodb_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data: 