global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'recipe-service'
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'ingredient-scanner-service'
    static_configs:
      - targets: ['host.docker.internal:8002']

  - job_name: 'meal-planning-service'
    static_configs:
      - targets: ['host.docker.internal:8003']

  - job_name: 'shopping-list-service'
    static_configs:
      - targets: ['host.docker.internal:8004']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692'] 